CREATE DATABASE IF NOT EXISTS Kitbox;
USE Kitbox;

DROP TABLE IF EXISTS LOCKER;
DROP TABLE IF EXISTS CABINET;
DROP TABLE IF EXISTS COMMANDE;
DROP TABLE IF EXISTS bill;

CREATE TABLE BILL (
    NBILL CHAR(5) NOT NULL,
    EMISSION_DATE DATE NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (NBILL)
);

CREATE TABLE COMMANDE (
    NCOM CHAR(5) NOT NULL,
    NCLI CHAR(5) NOT NULL,
    NBILL CHAR(5),
    DATE_COMMANDE DATE NOT NULL,
    DEPOSIT DATE,
    AVAILABLE_DATE DATE,
    PRIMARY KEY (NCOM),
    FOREIGN KEY (NBILL) REFERENCES BILL(NBILL)
);

CREATE TABLE CABINET (
	NCAB CHAR(5) NOT NULL,
	NCOM CHAR(5) NOT NULL,
	HEIGHT INT NOT NULL,
	NLOCKER INT NOT NULL,
	PRIMARY KEY (NCAB),
	FOREIGN KEY (NCOM) REFERENCES COMMANDE(NCOM)
);

CREATE TABLE LOCKER (
	NLOCK CHAR(5) NOT NULL,
	NCAB CHAR(5) NOT NULL,
	HEIGHT INT NOT NULL,
	COLOR INT NOT NULL,
	WITDTH INT NOT NULL,
	DEPTH INT NOT NULL,
	PRIMARY KEY (NLOCK),
	FOREIGN KEY (NCAB) REFERENCES CABINET(NCAB)
	);
	
SHOW TABLES;
